name: Eleventy Build

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: [main]
  schedule:
    - cron: "0 */2 * * *" # every 2 hours

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout uhack repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.3"

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r _data/requirements.txt

      - name: Scrape GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          cd _data
          python scrape_github.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "🏆 update hackathon results 🏆" -a

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main
          force: true

  build_deploy:
    needs: update_data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build --if-present

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v1.1.0
        env:
          PUBLISH_DIR: _site
          PUBLISH_BRANCH: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
