name: Update hackathon results

on:
  workflow_dispatch:
    inputs: {}
  schedule:
    - cron: "0 */2 * * *" # every 2 hours

jobs:
  update_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout uhack repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.3"

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r _data/requirements.txt

      - name: Scrape GitHub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd _data
          python scrape_github.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "🏆 update hackathon results 🏆" -a

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          force: true
